import { WebSocket } from 'ws';
import { updateTrustLevel, updateFearIndex, getOrCreateSession } from './db';
import { generateSceneImage } from './imagen';
import { generateSceneVideo } from './veo';
import type { LiveSessionManager } from './gemini';

/**
 * Handles a function call dispatched by the Gemini Game Master.
 * Persists the state change to Firestore and broadcasts the event
 * over WebSocket to the connected frontend client.
 * jasonManager, if provided, receives a live trust-context update so Jason's
 * in-flight Gemini session adapts immediately — not just on the next connect.
 */
export async function handleGmFunctionCall(
  sessionId: string,
  functionName: string,
  args: Record<string, unknown>,
  clientWs: WebSocket,
  jasonManager?: LiveSessionManager
): Promise<void> {
  console.log(`[GM] Function call: ${functionName}`, args);

  let wsMessage: Record<string, unknown> | null = null;

  switch (functionName) {
    case 'triggerTrustChange': {
      const levelMap: Record<string, number> = { High: 0.8, Neutral: 0.5, Low: 0.2 };
      const newLevel = levelMap[args.newTrustLevel as string] ?? 0.5;
      await updateTrustLevel(sessionId, newLevel);
      const session = await getOrCreateSession(sessionId);
      wsMessage = {
        type: 'trust_update',
        agent: 'gm',
        trust_level: newLevel,
        fear_index: session.fearIndex
      };
      // Push live trust context into Jason's running Gemini session so his
      // behaviour adapts immediately without waiting for a reconnect.
      if (jasonManager) {
        jasonManager.sendText(
          `[TRUST_SYSTEM: trust_level is now ${newLevel.toFixed(2)} — ` +
          `reason: ${args.reason ?? 'unspecified'}. Adjust your behaviour accordingly.]`
        );
        console.log(`[GM] Injected trust context into Jason — level: ${newLevel.toFixed(2)}`);
      }
      break;
    }

    case 'triggerFearChange': {
      const newFearLevel = Math.max(0, Math.min(1, args.newFearLevel as number));
      await updateFearIndex(sessionId, newFearLevel);
      const fearSession = await getOrCreateSession(sessionId);
      wsMessage = {
        type: 'trust_update',
        agent: 'gm',
        trust_level: fearSession.trustLevel,
        fear_index: newFearLevel
      };
      if (jasonManager) {
        jasonManager.sendText(
          `[TRUST_SYSTEM: fear_index is now ${newFearLevel.toFixed(2)} — ` +
          `reason: ${args.reason ?? 'unspecified'}. Adjust your fear behaviour accordingly.]`
        );
        console.log(`[GM] Injected fear context into Jason — level: ${newFearLevel.toFixed(2)}`);
      }
      break;
    }

    case 'triggerGlitchEvent': {
      const durationMap: Record<string, number> = { low: 500, medium: 800, high: 1200 };
      const intensity = args.intensity as string;
      wsMessage = {
        type: 'hud_glitch',
        intensity,
        duration_ms: durationMap[intensity] ?? 800
      };
      break;
    }

    case 'triggerSceneChange': {
      const sceneKey = args.sceneKey as string;
      wsMessage = {
        type: 'scene_change',
        payload: { sceneKey }
      };
      // Fire Imagen 4 generation async — sends scene_image when ready (non-blocking)
      void generateSceneImage(sceneKey).then((base64) => {
        if (base64 && clientWs.readyState === WebSocket.OPEN) {
          clientWs.send(JSON.stringify({
            type: 'scene_image',
            agent: 'gm',
            sessionId,
            payload: { sceneKey, data: base64 },
            timestamp: Date.now()
          }));
          console.log(`[GM] Broadcast scene_image — sceneKey="${sceneKey}"`);
        }
      });
      break;
    }

    case 'triggerSlotsky': {
      wsMessage = {
        type: 'slotsky_trigger',
        payload: { anomalyType: args.anomalyType }
      };
      break;
    }

    case 'triggerVideoGen': {
      const veoSceneKey = args.sceneKey as string;
      wsMessage = {
        type: 'video_gen_started',
        payload: { sceneKey: veoSceneKey }
      };
      // Fire Veo 3.1 Fast async — uses the last Imagen 4 still for this session.
      // The still image must already have been generated by triggerSceneChange.
      // We re-generate the image bytes here (cached by Imagen if called recently)
      // to pass as the reference frame for Veo.
      void (async () => {
        try {
          const base64Jpeg = await generateSceneImage(veoSceneKey);
          if (!base64Jpeg) {
            console.warn(`[GM] No image available for Veo — sceneKey="${veoSceneKey}". Skipping video gen.`);
            return;
          }
          const videoUri = await generateSceneVideo(veoSceneKey, base64Jpeg);
          if (videoUri && clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({
              type: 'scene_video',
              agent: 'gm',
              sessionId,
              payload: { sceneKey: veoSceneKey, url: videoUri },
              timestamp: Date.now()
            }));
            console.log(`[GM] Broadcast scene_video — sceneKey="${veoSceneKey}"`);
          }
        } catch (err) {
          console.error(`[GM] Veo pipeline failed for sceneKey="${veoSceneKey}":`, (err as Error).message);
        }
      })();
      break;
    }

    default:
      console.warn(`[GM] Unknown function call received: ${functionName}`);
      return;
  }

  if (wsMessage && clientWs.readyState === WebSocket.OPEN) {
    clientWs.send(JSON.stringify(wsMessage));
    console.log(`[GM] Broadcast event to client: ${wsMessage.type}`);
  }
}
